// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/admin.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TurboDBAdmin_Health_FullMethodName            = "/turbodb.v1.TurboDBAdmin/Health"
	TurboDBAdmin_Ready_FullMethodName             = "/turbodb.v1.TurboDBAdmin/Ready"
	TurboDBAdmin_GPUInfo_FullMethodName           = "/turbodb.v1.TurboDBAdmin/GPUInfo"
	TurboDBAdmin_RotatorRegenerate_FullMethodName = "/turbodb.v1.TurboDBAdmin/RotatorRegenerate"
	TurboDBAdmin_CodebookUpgrade_FullMethodName   = "/turbodb.v1.TurboDBAdmin/CodebookUpgrade"
)

// TurboDBAdminClient is the client API for TurboDBAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TurboDBAdmin provides administrative and operational endpoints.
type TurboDBAdminClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
	GPUInfo(ctx context.Context, in *GPUInfoRequest, opts ...grpc.CallOption) (*GPUInfoResponse, error)
	RotatorRegenerate(ctx context.Context, in *RotatorRegenerateRequest, opts ...grpc.CallOption) (*RotatorRegenerateResponse, error)
	CodebookUpgrade(ctx context.Context, in *CodebookUpgradeRequest, opts ...grpc.CallOption) (*CodebookUpgradeResponse, error)
}

type turboDBAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewTurboDBAdminClient(cc grpc.ClientConnInterface) TurboDBAdminClient {
	return &turboDBAdminClient{cc}
}

func (c *turboDBAdminClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TurboDBAdmin_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBAdminClient) Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, TurboDBAdmin_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBAdminClient) GPUInfo(ctx context.Context, in *GPUInfoRequest, opts ...grpc.CallOption) (*GPUInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPUInfoResponse)
	err := c.cc.Invoke(ctx, TurboDBAdmin_GPUInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBAdminClient) RotatorRegenerate(ctx context.Context, in *RotatorRegenerateRequest, opts ...grpc.CallOption) (*RotatorRegenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotatorRegenerateResponse)
	err := c.cc.Invoke(ctx, TurboDBAdmin_RotatorRegenerate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBAdminClient) CodebookUpgrade(ctx context.Context, in *CodebookUpgradeRequest, opts ...grpc.CallOption) (*CodebookUpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodebookUpgradeResponse)
	err := c.cc.Invoke(ctx, TurboDBAdmin_CodebookUpgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurboDBAdminServer is the server API for TurboDBAdmin service.
// All implementations must embed UnimplementedTurboDBAdminServer
// for forward compatibility.
//
// TurboDBAdmin provides administrative and operational endpoints.
type TurboDBAdminServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Ready(context.Context, *ReadyRequest) (*ReadyResponse, error)
	GPUInfo(context.Context, *GPUInfoRequest) (*GPUInfoResponse, error)
	RotatorRegenerate(context.Context, *RotatorRegenerateRequest) (*RotatorRegenerateResponse, error)
	CodebookUpgrade(context.Context, *CodebookUpgradeRequest) (*CodebookUpgradeResponse, error)
	mustEmbedUnimplementedTurboDBAdminServer()
}

// UnimplementedTurboDBAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTurboDBAdminServer struct{}

func (UnimplementedTurboDBAdminServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTurboDBAdminServer) Ready(context.Context, *ReadyRequest) (*ReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedTurboDBAdminServer) GPUInfo(context.Context, *GPUInfoRequest) (*GPUInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GPUInfo not implemented")
}
func (UnimplementedTurboDBAdminServer) RotatorRegenerate(context.Context, *RotatorRegenerateRequest) (*RotatorRegenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotatorRegenerate not implemented")
}
func (UnimplementedTurboDBAdminServer) CodebookUpgrade(context.Context, *CodebookUpgradeRequest) (*CodebookUpgradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CodebookUpgrade not implemented")
}
func (UnimplementedTurboDBAdminServer) mustEmbedUnimplementedTurboDBAdminServer() {}
func (UnimplementedTurboDBAdminServer) testEmbeddedByValue()                      {}

// UnsafeTurboDBAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurboDBAdminServer will
// result in compilation errors.
type UnsafeTurboDBAdminServer interface {
	mustEmbedUnimplementedTurboDBAdminServer()
}

func RegisterTurboDBAdminServer(s grpc.ServiceRegistrar, srv TurboDBAdminServer) {
	// If the following call panics, it indicates UnimplementedTurboDBAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TurboDBAdmin_ServiceDesc, srv)
}

func _TurboDBAdmin_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBAdminServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBAdmin_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBAdminServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBAdmin_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBAdminServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBAdmin_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBAdminServer).Ready(ctx, req.(*ReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBAdmin_GPUInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPUInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBAdminServer).GPUInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBAdmin_GPUInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBAdminServer).GPUInfo(ctx, req.(*GPUInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBAdmin_RotatorRegenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotatorRegenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBAdminServer).RotatorRegenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBAdmin_RotatorRegenerate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBAdminServer).RotatorRegenerate(ctx, req.(*RotatorRegenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBAdmin_CodebookUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodebookUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBAdminServer).CodebookUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBAdmin_CodebookUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBAdminServer).CodebookUpgrade(ctx, req.(*CodebookUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TurboDBAdmin_ServiceDesc is the grpc.ServiceDesc for TurboDBAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TurboDBAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turbodb.v1.TurboDBAdmin",
	HandlerType: (*TurboDBAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _TurboDBAdmin_Health_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _TurboDBAdmin_Ready_Handler,
		},
		{
			MethodName: "GPUInfo",
			Handler:    _TurboDBAdmin_GPUInfo_Handler,
		},
		{
			MethodName: "RotatorRegenerate",
			Handler:    _TurboDBAdmin_RotatorRegenerate_Handler,
		},
		{
			MethodName: "CodebookUpgrade",
			Handler:    _TurboDBAdmin_CodebookUpgrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin.proto",
}
