// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/admin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{2}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GPUInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfoRequest) Reset() {
	*x = GPUInfoRequest{}
	mi := &file_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfoRequest) ProtoMessage() {}

func (x *GPUInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfoRequest.ProtoReflect.Descriptor instead.
func (*GPUInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{4}
}

type GPUDevice struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalMemoryBytes  int64                  `protobuf:"varint,3,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	FreeMemoryBytes   int64                  `protobuf:"varint,4,opt,name=free_memory_bytes,json=freeMemoryBytes,proto3" json:"free_memory_bytes,omitempty"`
	ComputeCapability string                 `protobuf:"bytes,5,opt,name=compute_capability,json=computeCapability,proto3" json:"compute_capability,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GPUDevice) Reset() {
	*x = GPUDevice{}
	mi := &file_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUDevice) ProtoMessage() {}

func (x *GPUDevice) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUDevice.ProtoReflect.Descriptor instead.
func (*GPUDevice) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GPUDevice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GPUDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUDevice) GetTotalMemoryBytes() int64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *GPUDevice) GetFreeMemoryBytes() int64 {
	if x != nil {
		return x.FreeMemoryBytes
	}
	return 0
}

func (x *GPUDevice) GetComputeCapability() string {
	if x != nil {
		return x.ComputeCapability
	}
	return ""
}

type GPUInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*GPUDevice           `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	CudaVersion   string                 `protobuf:"bytes,2,opt,name=cuda_version,json=cudaVersion,proto3" json:"cuda_version,omitempty"`
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfoResponse) Reset() {
	*x = GPUInfoResponse{}
	mi := &file_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfoResponse) ProtoMessage() {}

func (x *GPUInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfoResponse.ProtoReflect.Descriptor instead.
func (*GPUInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GPUInfoResponse) GetDevices() []*GPUDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GPUInfoResponse) GetCudaVersion() string {
	if x != nil {
		return x.CudaVersion
	}
	return ""
}

func (x *GPUInfoResponse) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

type RotatorRegenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Confirm       string                 `protobuf:"bytes,2,opt,name=confirm,proto3" json:"confirm,omitempty"` // Must be "i understand this will invalidate all indexes"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotatorRegenerateRequest) Reset() {
	*x = RotatorRegenerateRequest{}
	mi := &file_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotatorRegenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotatorRegenerateRequest) ProtoMessage() {}

func (x *RotatorRegenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotatorRegenerateRequest.ProtoReflect.Descriptor instead.
func (*RotatorRegenerateRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RotatorRegenerateRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *RotatorRegenerateRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

type RotatorRegenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSeed       uint64                 `protobuf:"varint,1,opt,name=new_seed,json=newSeed,proto3" json:"new_seed,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotatorRegenerateResponse) Reset() {
	*x = RotatorRegenerateResponse{}
	mi := &file_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotatorRegenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotatorRegenerateResponse) ProtoMessage() {}

func (x *RotatorRegenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotatorRegenerateResponse.ProtoReflect.Descriptor instead.
func (*RotatorRegenerateResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RotatorRegenerateResponse) GetNewSeed() uint64 {
	if x != nil {
		return x.NewSeed
	}
	return 0
}

func (x *RotatorRegenerateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CodebookUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	FromVersion   string                 `protobuf:"bytes,2,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion     string                 `protobuf:"bytes,3,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodebookUpgradeRequest) Reset() {
	*x = CodebookUpgradeRequest{}
	mi := &file_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodebookUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodebookUpgradeRequest) ProtoMessage() {}

func (x *CodebookUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodebookUpgradeRequest.ProtoReflect.Descriptor instead.
func (*CodebookUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CodebookUpgradeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CodebookUpgradeRequest) GetFromVersion() string {
	if x != nil {
		return x.FromVersion
	}
	return ""
}

func (x *CodebookUpgradeRequest) GetToVersion() string {
	if x != nil {
		return x.ToVersion
	}
	return ""
}

type CodebookUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodebookUpgradeResponse) Reset() {
	*x = CodebookUpgradeResponse{}
	mi := &file_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodebookUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodebookUpgradeResponse) ProtoMessage() {}

func (x *CodebookUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodebookUpgradeResponse.ProtoReflect.Descriptor instead.
func (*CodebookUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *CodebookUpgradeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_admin_proto protoreflect.FileDescriptor

const file_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/admin.proto\x12\n" +
	"turbodb.v1\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\"\x0e\n" +
	"\fReadyRequest\"=\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x10\n" +
	"\x0eGPUInfoRequest\"\xb8\x01\n" +
	"\tGPUDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x12total_memory_bytes\x18\x03 \x01(\x03R\x10totalMemoryBytes\x12*\n" +
	"\x11free_memory_bytes\x18\x04 \x01(\x03R\x0ffreeMemoryBytes\x12-\n" +
	"\x12compute_capability\x18\x05 \x01(\tR\x11computeCapability\"\x8c\x01\n" +
	"\x0fGPUInfoResponse\x12/\n" +
	"\adevices\x18\x01 \x03(\v2\x15.turbodb.v1.GPUDeviceR\adevices\x12!\n" +
	"\fcuda_version\x18\x02 \x01(\tR\vcudaVersion\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\"T\n" +
	"\x18RotatorRegenerateRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x18\n" +
	"\aconfirm\x18\x02 \x01(\tR\aconfirm\"P\n" +
	"\x19RotatorRegenerateResponse\x12\x19\n" +
	"\bnew_seed\x18\x01 \x01(\x04R\anewSeed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"z\n" +
	"\x16CodebookUpgradeRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\ffrom_version\x18\x02 \x01(\tR\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x03 \x01(\tR\ttoVersion\"3\n" +
	"\x17CodebookUpgradeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8f\x03\n" +
	"\fTurboDBAdmin\x12?\n" +
	"\x06Health\x12\x19.turbodb.v1.HealthRequest\x1a\x1a.turbodb.v1.HealthResponse\x12<\n" +
	"\x05Ready\x12\x18.turbodb.v1.ReadyRequest\x1a\x19.turbodb.v1.ReadyResponse\x12B\n" +
	"\aGPUInfo\x12\x1a.turbodb.v1.GPUInfoRequest\x1a\x1b.turbodb.v1.GPUInfoResponse\x12`\n" +
	"\x11RotatorRegenerate\x12$.turbodb.v1.RotatorRegenerateRequest\x1a%.turbodb.v1.RotatorRegenerateResponse\x12Z\n" +
	"\x0fCodebookUpgrade\x12\".turbodb.v1.CodebookUpgradeRequest\x1a#.turbodb.v1.CodebookUpgradeResponseB.Z,github.com/gabrielleeyj/turbodb/api/v1;apiv1b\x06proto3"

var (
	file_v1_admin_proto_rawDescOnce sync.Once
	file_v1_admin_proto_rawDescData []byte
)

func file_v1_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)))
	})
	return file_v1_admin_proto_rawDescData
}

var file_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_admin_proto_goTypes = []any{
	(*HealthRequest)(nil),             // 0: turbodb.v1.HealthRequest
	(*HealthResponse)(nil),            // 1: turbodb.v1.HealthResponse
	(*ReadyRequest)(nil),              // 2: turbodb.v1.ReadyRequest
	(*ReadyResponse)(nil),             // 3: turbodb.v1.ReadyResponse
	(*GPUInfoRequest)(nil),            // 4: turbodb.v1.GPUInfoRequest
	(*GPUDevice)(nil),                 // 5: turbodb.v1.GPUDevice
	(*GPUInfoResponse)(nil),           // 6: turbodb.v1.GPUInfoResponse
	(*RotatorRegenerateRequest)(nil),  // 7: turbodb.v1.RotatorRegenerateRequest
	(*RotatorRegenerateResponse)(nil), // 8: turbodb.v1.RotatorRegenerateResponse
	(*CodebookUpgradeRequest)(nil),    // 9: turbodb.v1.CodebookUpgradeRequest
	(*CodebookUpgradeResponse)(nil),   // 10: turbodb.v1.CodebookUpgradeResponse
}
var file_v1_admin_proto_depIdxs = []int32{
	5,  // 0: turbodb.v1.GPUInfoResponse.devices:type_name -> turbodb.v1.GPUDevice
	0,  // 1: turbodb.v1.TurboDBAdmin.Health:input_type -> turbodb.v1.HealthRequest
	2,  // 2: turbodb.v1.TurboDBAdmin.Ready:input_type -> turbodb.v1.ReadyRequest
	4,  // 3: turbodb.v1.TurboDBAdmin.GPUInfo:input_type -> turbodb.v1.GPUInfoRequest
	7,  // 4: turbodb.v1.TurboDBAdmin.RotatorRegenerate:input_type -> turbodb.v1.RotatorRegenerateRequest
	9,  // 5: turbodb.v1.TurboDBAdmin.CodebookUpgrade:input_type -> turbodb.v1.CodebookUpgradeRequest
	1,  // 6: turbodb.v1.TurboDBAdmin.Health:output_type -> turbodb.v1.HealthResponse
	3,  // 7: turbodb.v1.TurboDBAdmin.Ready:output_type -> turbodb.v1.ReadyResponse
	6,  // 8: turbodb.v1.TurboDBAdmin.GPUInfo:output_type -> turbodb.v1.GPUInfoResponse
	8,  // 9: turbodb.v1.TurboDBAdmin.RotatorRegenerate:output_type -> turbodb.v1.RotatorRegenerateResponse
	10, // 10: turbodb.v1.TurboDBAdmin.CodebookUpgrade:output_type -> turbodb.v1.CodebookUpgradeResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_v1_admin_proto_init() }
func file_v1_admin_proto_init() {
	if File_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_proto_depIdxs,
		MessageInfos:      file_v1_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_proto = out.File
	file_v1_admin_proto_goTypes = nil
	file_v1_admin_proto_depIdxs = nil
}
