// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/engine.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TurboDBEngine_CreateCollection_FullMethodName   = "/turbodb.v1.TurboDBEngine/CreateCollection"
	TurboDBEngine_DropCollection_FullMethodName     = "/turbodb.v1.TurboDBEngine/DropCollection"
	TurboDBEngine_ListCollections_FullMethodName    = "/turbodb.v1.TurboDBEngine/ListCollections"
	TurboDBEngine_DescribeCollection_FullMethodName = "/turbodb.v1.TurboDBEngine/DescribeCollection"
	TurboDBEngine_Insert_FullMethodName             = "/turbodb.v1.TurboDBEngine/Insert"
	TurboDBEngine_InsertBatch_FullMethodName        = "/turbodb.v1.TurboDBEngine/InsertBatch"
	TurboDBEngine_Delete_FullMethodName             = "/turbodb.v1.TurboDBEngine/Delete"
	TurboDBEngine_Search_FullMethodName             = "/turbodb.v1.TurboDBEngine/Search"
	TurboDBEngine_SearchBatch_FullMethodName        = "/turbodb.v1.TurboDBEngine/SearchBatch"
	TurboDBEngine_Flush_FullMethodName              = "/turbodb.v1.TurboDBEngine/Flush"
	TurboDBEngine_GetStats_FullMethodName           = "/turbodb.v1.TurboDBEngine/GetStats"
)

// TurboDBEngineClient is the client API for TurboDBEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TurboDBEngine is the primary gRPC service for the standalone vector engine.
type TurboDBEngineClient interface {
	// Collection management
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*DropCollectionResponse, error)
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	DescribeCollection(ctx context.Context, in *DescribeCollectionRequest, opts ...grpc.CallOption) (*DescribeCollectionResponse, error)
	// Data operations
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	InsertBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertBatchRequest, InsertBatchResponse], error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchBatchResponse], error)
	// Maintenance
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type turboDBEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewTurboDBEngineClient(cc grpc.ClientConnInterface) TurboDBEngineClient {
	return &turboDBEngineClient{cc}
}

func (c *turboDBEngineClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) DropCollection(ctx context.Context, in *DropCollectionRequest, opts ...grpc.CallOption) (*DropCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropCollectionResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_DropCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) DescribeCollection(ctx context.Context, in *DescribeCollectionRequest, opts ...grpc.CallOption) (*DescribeCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeCollectionResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_DescribeCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) InsertBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InsertBatchRequest, InsertBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TurboDBEngine_ServiceDesc.Streams[0], TurboDBEngine_InsertBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InsertBatchRequest, InsertBatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurboDBEngine_InsertBatchClient = grpc.ClientStreamingClient[InsertBatchRequest, InsertBatchResponse]

func (c *turboDBEngineClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TurboDBEngine_ServiceDesc.Streams[1], TurboDBEngine_SearchBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchBatchRequest, SearchBatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurboDBEngine_SearchBatchClient = grpc.ServerStreamingClient[SearchBatchResponse]

func (c *turboDBEngineClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboDBEngineClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, TurboDBEngine_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurboDBEngineServer is the server API for TurboDBEngine service.
// All implementations must embed UnimplementedTurboDBEngineServer
// for forward compatibility.
//
// TurboDBEngine is the primary gRPC service for the standalone vector engine.
type TurboDBEngineServer interface {
	// Collection management
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	DropCollection(context.Context, *DropCollectionRequest) (*DropCollectionResponse, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	DescribeCollection(context.Context, *DescribeCollectionRequest) (*DescribeCollectionResponse, error)
	// Data operations
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	InsertBatch(grpc.ClientStreamingServer[InsertBatchRequest, InsertBatchResponse]) error
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchBatch(*SearchBatchRequest, grpc.ServerStreamingServer[SearchBatchResponse]) error
	// Maintenance
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedTurboDBEngineServer()
}

// UnimplementedTurboDBEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTurboDBEngineServer struct{}

func (UnimplementedTurboDBEngineServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedTurboDBEngineServer) DropCollection(context.Context, *DropCollectionRequest) (*DropCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropCollection not implemented")
}
func (UnimplementedTurboDBEngineServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedTurboDBEngineServer) DescribeCollection(context.Context, *DescribeCollectionRequest) (*DescribeCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeCollection not implemented")
}
func (UnimplementedTurboDBEngineServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedTurboDBEngineServer) InsertBatch(grpc.ClientStreamingServer[InsertBatchRequest, InsertBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method InsertBatch not implemented")
}
func (UnimplementedTurboDBEngineServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTurboDBEngineServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedTurboDBEngineServer) SearchBatch(*SearchBatchRequest, grpc.ServerStreamingServer[SearchBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method SearchBatch not implemented")
}
func (UnimplementedTurboDBEngineServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedTurboDBEngineServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedTurboDBEngineServer) mustEmbedUnimplementedTurboDBEngineServer() {}
func (UnimplementedTurboDBEngineServer) testEmbeddedByValue()                       {}

// UnsafeTurboDBEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurboDBEngineServer will
// result in compilation errors.
type UnsafeTurboDBEngineServer interface {
	mustEmbedUnimplementedTurboDBEngineServer()
}

func RegisterTurboDBEngineServer(s grpc.ServiceRegistrar, srv TurboDBEngineServer) {
	// If the following call panics, it indicates UnimplementedTurboDBEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TurboDBEngine_ServiceDesc, srv)
}

func _TurboDBEngine_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_DropCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).DropCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_DropCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).DropCollection(ctx, req.(*DropCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_DescribeCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).DescribeCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_DescribeCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).DescribeCollection(ctx, req.(*DescribeCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_InsertBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TurboDBEngineServer).InsertBatch(&grpc.GenericServerStream[InsertBatchRequest, InsertBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurboDBEngine_InsertBatchServer = grpc.ClientStreamingServer[InsertBatchRequest, InsertBatchResponse]

func _TurboDBEngine_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_SearchBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TurboDBEngineServer).SearchBatch(m, &grpc.GenericServerStream[SearchBatchRequest, SearchBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurboDBEngine_SearchBatchServer = grpc.ServerStreamingServer[SearchBatchResponse]

func _TurboDBEngine_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboDBEngine_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboDBEngineServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboDBEngine_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboDBEngineServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TurboDBEngine_ServiceDesc is the grpc.ServiceDesc for TurboDBEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TurboDBEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turbodb.v1.TurboDBEngine",
	HandlerType: (*TurboDBEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _TurboDBEngine_CreateCollection_Handler,
		},
		{
			MethodName: "DropCollection",
			Handler:    _TurboDBEngine_DropCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _TurboDBEngine_ListCollections_Handler,
		},
		{
			MethodName: "DescribeCollection",
			Handler:    _TurboDBEngine_DescribeCollection_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _TurboDBEngine_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TurboDBEngine_Delete_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _TurboDBEngine_Search_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _TurboDBEngine_Flush_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _TurboDBEngine_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InsertBatch",
			Handler:       _TurboDBEngine_InsertBatch_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SearchBatch",
			Handler:       _TurboDBEngine_SearchBatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/engine.proto",
}
