// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/engine.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CollectionConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCollectionRequest) GetConfig() *CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCollectionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *DropCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionResponse) Reset() {
	*x = DropCollectionResponse{}
	mi := &file_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionResponse) ProtoMessage() {}

func (x *DropCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionResponse.ProtoReflect.Descriptor instead.
func (*DropCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{3}
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{4}
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionConfig    `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionConfig {
	if x != nil {
		return x.Collections
	}
	return nil
}

type DescribeCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCollectionRequest) Reset() {
	*x = DescribeCollectionRequest{}
	mi := &file_v1_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCollectionRequest) ProtoMessage() {}

func (x *DescribeCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCollectionRequest.ProtoReflect.Descriptor instead.
func (*DescribeCollectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DescribeCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CollectionConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Stats         *CollectionStats       `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeCollectionResponse) Reset() {
	*x = DescribeCollectionResponse{}
	mi := &file_v1_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeCollectionResponse) ProtoMessage() {}

func (x *DescribeCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeCollectionResponse.ProtoReflect.Descriptor instead.
func (*DescribeCollectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeCollectionResponse) GetConfig() *CollectionConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DescribeCollectionResponse) GetStats() *CollectionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CollectionStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	VectorCount         int64                  `protobuf:"varint,1,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	SealedSegmentCount  int32                  `protobuf:"varint,2,opt,name=sealed_segment_count,json=sealedSegmentCount,proto3" json:"sealed_segment_count,omitempty"`
	GrowingSegmentCount int32                  `protobuf:"varint,3,opt,name=growing_segment_count,json=growingSegmentCount,proto3" json:"growing_segment_count,omitempty"`
	GpuMemoryBytes      int64                  `protobuf:"varint,4,opt,name=gpu_memory_bytes,json=gpuMemoryBytes,proto3" json:"gpu_memory_bytes,omitempty"`
	HostMemoryBytes     int64                  `protobuf:"varint,5,opt,name=host_memory_bytes,json=hostMemoryBytes,proto3" json:"host_memory_bytes,omitempty"`
	DiskBytes           int64                  `protobuf:"varint,6,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CollectionStats) Reset() {
	*x = CollectionStats{}
	mi := &file_v1_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionStats) ProtoMessage() {}

func (x *CollectionStats) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionStats.ProtoReflect.Descriptor instead.
func (*CollectionStats) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{8}
}

func (x *CollectionStats) GetVectorCount() int64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *CollectionStats) GetSealedSegmentCount() int32 {
	if x != nil {
		return x.SealedSegmentCount
	}
	return 0
}

func (x *CollectionStats) GetGrowingSegmentCount() int32 {
	if x != nil {
		return x.GrowingSegmentCount
	}
	return 0
}

func (x *CollectionStats) GetGpuMemoryBytes() int64 {
	if x != nil {
		return x.GpuMemoryBytes
	}
	return 0
}

func (x *CollectionStats) GetHostMemoryBytes() int64 {
	if x != nil {
		return x.HostMemoryBytes
	}
	return 0
}

func (x *CollectionStats) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_v1_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{9}
}

func (x *InsertRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertRequest) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_v1_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{10}
}

func (x *InsertResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InsertBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Vectors       []*Vector              `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertBatchRequest) Reset() {
	*x = InsertBatchRequest{}
	mi := &file_v1_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBatchRequest) ProtoMessage() {}

func (x *InsertBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBatchRequest.ProtoReflect.Descriptor instead.
func (*InsertBatchRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{11}
}

func (x *InsertBatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertBatchRequest) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type InsertBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount int64                  `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertBatchResponse) Reset() {
	*x = InsertBatchResponse{}
	mi := &file_v1_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBatchResponse) ProtoMessage() {}

func (x *InsertBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBatchResponse.ProtoReflect.Descriptor instead.
func (*InsertBatchResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{12}
}

func (x *InsertBatchResponse) GetInsertedCount() int64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_v1_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{14}
}

// SearchRequest performs a similarity search.
// Validation constraints (enforced at server boundary):
//
//	collection: non-empty
//	query:      len == collection.dimension; no NaN/Inf
//	top_k:      1..1000
//	ef_search:  0 (default) or >= top_k
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Query         []float32              `protobuf:"fixed32,2,rep,packed,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Rerank        bool                   `protobuf:"varint,4,opt,name=rerank,proto3" json:"rerank,omitempty"`
	EfSearch      int32                  `protobuf:"varint,5,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	Exact         bool                   `protobuf:"varint,6,opt,name=exact,proto3" json:"exact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_v1_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{15}
}

func (x *SearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetRerank() bool {
	if x != nil {
		return x.Rerank
	}
	return false
}

func (x *SearchRequest) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *SearchRequest) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	SearchTimeUs  int64                  `protobuf:"varint,2,opt,name=search_time_us,json=searchTimeUs,proto3" json:"search_time_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_v1_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetSearchTimeUs() int64 {
	if x != nil {
		return x.SearchTimeUs
	}
	return 0
}

type SearchBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Queries       []*SearchRequest       `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchRequest) Reset() {
	*x = SearchBatchRequest{}
	mi := &file_v1_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchRequest) ProtoMessage() {}

func (x *SearchBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchRequest.ProtoReflect.Descriptor instead.
func (*SearchBatchRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{17}
}

func (x *SearchBatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchBatchRequest) GetQueries() []*SearchRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

type SearchBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *SearchResponse        `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchBatchResponse) Reset() {
	*x = SearchBatchResponse{}
	mi := &file_v1_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBatchResponse) ProtoMessage() {}

func (x *SearchBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBatchResponse.ProtoReflect.Descriptor instead.
func (*SearchBatchResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{18}
}

func (x *SearchBatchResponse) GetResponse() *SearchResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_v1_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{19}
}

func (x *FlushRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type FlushResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SegmentsSealed int32                  `protobuf:"varint,1,opt,name=segments_sealed,json=segmentsSealed,proto3" json:"segments_sealed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_v1_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{20}
}

func (x *FlushResponse) GetSegmentsSealed() int32 {
	if x != nil {
		return x.SegmentsSealed
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_v1_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *CollectionStats       `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_v1_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_v1_engine_proto_rawDescGZIP(), []int{22}
}

func (x *GetStatsResponse) GetStats() *CollectionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_v1_engine_proto protoreflect.FileDescriptor

const file_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/engine.proto\x12\n" +
	"turbodb.v1\x1a\x0ev1/index.proto\"O\n" +
	"\x17CreateCollectionRequest\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.turbodb.v1.CollectionConfigR\x06config\".\n" +
	"\x18CreateCollectionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15DropCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16DropCollectionResponse\"\x18\n" +
	"\x16ListCollectionsRequest\"Y\n" +
	"\x17ListCollectionsResponse\x12>\n" +
	"\vcollections\x18\x01 \x03(\v2\x1c.turbodb.v1.CollectionConfigR\vcollections\"/\n" +
	"\x19DescribeCollectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x85\x01\n" +
	"\x1aDescribeCollectionResponse\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.turbodb.v1.CollectionConfigR\x06config\x121\n" +
	"\x05stats\x18\x02 \x01(\v2\x1b.turbodb.v1.CollectionStatsR\x05stats\"\x8f\x02\n" +
	"\x0fCollectionStats\x12!\n" +
	"\fvector_count\x18\x01 \x01(\x03R\vvectorCount\x120\n" +
	"\x14sealed_segment_count\x18\x02 \x01(\x05R\x12sealedSegmentCount\x122\n" +
	"\x15growing_segment_count\x18\x03 \x01(\x05R\x13growingSegmentCount\x12(\n" +
	"\x10gpu_memory_bytes\x18\x04 \x01(\x03R\x0egpuMemoryBytes\x12*\n" +
	"\x11host_memory_bytes\x18\x05 \x01(\x03R\x0fhostMemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x06 \x01(\x03R\tdiskBytes\"[\n" +
	"\rInsertRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12*\n" +
	"\x06vector\x18\x02 \x01(\v2\x12.turbodb.v1.VectorR\x06vector\" \n" +
	"\x0eInsertResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x12InsertBatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12,\n" +
	"\avectors\x18\x02 \x03(\v2\x12.turbodb.v1.VectorR\avectors\"<\n" +
	"\x13InsertBatchResponse\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x03R\rinsertedCount\"?\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"\xa5\x01\n" +
	"\rSearchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x02 \x03(\x02R\x05query\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x16\n" +
	"\x06rerank\x18\x04 \x01(\bR\x06rerank\x12\x1b\n" +
	"\tef_search\x18\x05 \x01(\x05R\befSearch\x12\x14\n" +
	"\x05exact\x18\x06 \x01(\bR\x05exact\"j\n" +
	"\x0eSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.turbodb.v1.SearchResultR\aresults\x12$\n" +
	"\x0esearch_time_us\x18\x02 \x01(\x03R\fsearchTimeUs\"i\n" +
	"\x12SearchBatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x123\n" +
	"\aqueries\x18\x02 \x03(\v2\x19.turbodb.v1.SearchRequestR\aqueries\"M\n" +
	"\x13SearchBatchResponse\x126\n" +
	"\bresponse\x18\x01 \x01(\v2\x1a.turbodb.v1.SearchResponseR\bresponse\".\n" +
	"\fFlushRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"8\n" +
	"\rFlushResponse\x12'\n" +
	"\x0fsegments_sealed\x18\x01 \x01(\x05R\x0esegmentsSealed\"1\n" +
	"\x0fGetStatsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\"E\n" +
	"\x10GetStatsResponse\x121\n" +
	"\x05stats\x18\x01 \x01(\v2\x1b.turbodb.v1.CollectionStatsR\x05stats2\xf4\x06\n" +
	"\rTurboDBEngine\x12]\n" +
	"\x10CreateCollection\x12#.turbodb.v1.CreateCollectionRequest\x1a$.turbodb.v1.CreateCollectionResponse\x12W\n" +
	"\x0eDropCollection\x12!.turbodb.v1.DropCollectionRequest\x1a\".turbodb.v1.DropCollectionResponse\x12Z\n" +
	"\x0fListCollections\x12\".turbodb.v1.ListCollectionsRequest\x1a#.turbodb.v1.ListCollectionsResponse\x12c\n" +
	"\x12DescribeCollection\x12%.turbodb.v1.DescribeCollectionRequest\x1a&.turbodb.v1.DescribeCollectionResponse\x12?\n" +
	"\x06Insert\x12\x19.turbodb.v1.InsertRequest\x1a\x1a.turbodb.v1.InsertResponse\x12P\n" +
	"\vInsertBatch\x12\x1e.turbodb.v1.InsertBatchRequest\x1a\x1f.turbodb.v1.InsertBatchResponse(\x01\x12?\n" +
	"\x06Delete\x12\x19.turbodb.v1.DeleteRequest\x1a\x1a.turbodb.v1.DeleteResponse\x12?\n" +
	"\x06Search\x12\x19.turbodb.v1.SearchRequest\x1a\x1a.turbodb.v1.SearchResponse\x12P\n" +
	"\vSearchBatch\x12\x1e.turbodb.v1.SearchBatchRequest\x1a\x1f.turbodb.v1.SearchBatchResponse0\x01\x12<\n" +
	"\x05Flush\x12\x18.turbodb.v1.FlushRequest\x1a\x19.turbodb.v1.FlushResponse\x12E\n" +
	"\bGetStats\x12\x1b.turbodb.v1.GetStatsRequest\x1a\x1c.turbodb.v1.GetStatsResponseB.Z,github.com/gabrielleeyj/turbodb/api/v1;apiv1b\x06proto3"

var (
	file_v1_engine_proto_rawDescOnce sync.Once
	file_v1_engine_proto_rawDescData []byte
)

func file_v1_engine_proto_rawDescGZIP() []byte {
	file_v1_engine_proto_rawDescOnce.Do(func() {
		file_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_engine_proto_rawDesc), len(file_v1_engine_proto_rawDesc)))
	})
	return file_v1_engine_proto_rawDescData
}

var file_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_v1_engine_proto_goTypes = []any{
	(*CreateCollectionRequest)(nil),    // 0: turbodb.v1.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),   // 1: turbodb.v1.CreateCollectionResponse
	(*DropCollectionRequest)(nil),      // 2: turbodb.v1.DropCollectionRequest
	(*DropCollectionResponse)(nil),     // 3: turbodb.v1.DropCollectionResponse
	(*ListCollectionsRequest)(nil),     // 4: turbodb.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),    // 5: turbodb.v1.ListCollectionsResponse
	(*DescribeCollectionRequest)(nil),  // 6: turbodb.v1.DescribeCollectionRequest
	(*DescribeCollectionResponse)(nil), // 7: turbodb.v1.DescribeCollectionResponse
	(*CollectionStats)(nil),            // 8: turbodb.v1.CollectionStats
	(*InsertRequest)(nil),              // 9: turbodb.v1.InsertRequest
	(*InsertResponse)(nil),             // 10: turbodb.v1.InsertResponse
	(*InsertBatchRequest)(nil),         // 11: turbodb.v1.InsertBatchRequest
	(*InsertBatchResponse)(nil),        // 12: turbodb.v1.InsertBatchResponse
	(*DeleteRequest)(nil),              // 13: turbodb.v1.DeleteRequest
	(*DeleteResponse)(nil),             // 14: turbodb.v1.DeleteResponse
	(*SearchRequest)(nil),              // 15: turbodb.v1.SearchRequest
	(*SearchResponse)(nil),             // 16: turbodb.v1.SearchResponse
	(*SearchBatchRequest)(nil),         // 17: turbodb.v1.SearchBatchRequest
	(*SearchBatchResponse)(nil),        // 18: turbodb.v1.SearchBatchResponse
	(*FlushRequest)(nil),               // 19: turbodb.v1.FlushRequest
	(*FlushResponse)(nil),              // 20: turbodb.v1.FlushResponse
	(*GetStatsRequest)(nil),            // 21: turbodb.v1.GetStatsRequest
	(*GetStatsResponse)(nil),           // 22: turbodb.v1.GetStatsResponse
	(*CollectionConfig)(nil),           // 23: turbodb.v1.CollectionConfig
	(*Vector)(nil),                     // 24: turbodb.v1.Vector
	(*SearchResult)(nil),               // 25: turbodb.v1.SearchResult
}
var file_v1_engine_proto_depIdxs = []int32{
	23, // 0: turbodb.v1.CreateCollectionRequest.config:type_name -> turbodb.v1.CollectionConfig
	23, // 1: turbodb.v1.ListCollectionsResponse.collections:type_name -> turbodb.v1.CollectionConfig
	23, // 2: turbodb.v1.DescribeCollectionResponse.config:type_name -> turbodb.v1.CollectionConfig
	8,  // 3: turbodb.v1.DescribeCollectionResponse.stats:type_name -> turbodb.v1.CollectionStats
	24, // 4: turbodb.v1.InsertRequest.vector:type_name -> turbodb.v1.Vector
	24, // 5: turbodb.v1.InsertBatchRequest.vectors:type_name -> turbodb.v1.Vector
	25, // 6: turbodb.v1.SearchResponse.results:type_name -> turbodb.v1.SearchResult
	15, // 7: turbodb.v1.SearchBatchRequest.queries:type_name -> turbodb.v1.SearchRequest
	16, // 8: turbodb.v1.SearchBatchResponse.response:type_name -> turbodb.v1.SearchResponse
	8,  // 9: turbodb.v1.GetStatsResponse.stats:type_name -> turbodb.v1.CollectionStats
	0,  // 10: turbodb.v1.TurboDBEngine.CreateCollection:input_type -> turbodb.v1.CreateCollectionRequest
	2,  // 11: turbodb.v1.TurboDBEngine.DropCollection:input_type -> turbodb.v1.DropCollectionRequest
	4,  // 12: turbodb.v1.TurboDBEngine.ListCollections:input_type -> turbodb.v1.ListCollectionsRequest
	6,  // 13: turbodb.v1.TurboDBEngine.DescribeCollection:input_type -> turbodb.v1.DescribeCollectionRequest
	9,  // 14: turbodb.v1.TurboDBEngine.Insert:input_type -> turbodb.v1.InsertRequest
	11, // 15: turbodb.v1.TurboDBEngine.InsertBatch:input_type -> turbodb.v1.InsertBatchRequest
	13, // 16: turbodb.v1.TurboDBEngine.Delete:input_type -> turbodb.v1.DeleteRequest
	15, // 17: turbodb.v1.TurboDBEngine.Search:input_type -> turbodb.v1.SearchRequest
	17, // 18: turbodb.v1.TurboDBEngine.SearchBatch:input_type -> turbodb.v1.SearchBatchRequest
	19, // 19: turbodb.v1.TurboDBEngine.Flush:input_type -> turbodb.v1.FlushRequest
	21, // 20: turbodb.v1.TurboDBEngine.GetStats:input_type -> turbodb.v1.GetStatsRequest
	1,  // 21: turbodb.v1.TurboDBEngine.CreateCollection:output_type -> turbodb.v1.CreateCollectionResponse
	3,  // 22: turbodb.v1.TurboDBEngine.DropCollection:output_type -> turbodb.v1.DropCollectionResponse
	5,  // 23: turbodb.v1.TurboDBEngine.ListCollections:output_type -> turbodb.v1.ListCollectionsResponse
	7,  // 24: turbodb.v1.TurboDBEngine.DescribeCollection:output_type -> turbodb.v1.DescribeCollectionResponse
	10, // 25: turbodb.v1.TurboDBEngine.Insert:output_type -> turbodb.v1.InsertResponse
	12, // 26: turbodb.v1.TurboDBEngine.InsertBatch:output_type -> turbodb.v1.InsertBatchResponse
	14, // 27: turbodb.v1.TurboDBEngine.Delete:output_type -> turbodb.v1.DeleteResponse
	16, // 28: turbodb.v1.TurboDBEngine.Search:output_type -> turbodb.v1.SearchResponse
	18, // 29: turbodb.v1.TurboDBEngine.SearchBatch:output_type -> turbodb.v1.SearchBatchResponse
	20, // 30: turbodb.v1.TurboDBEngine.Flush:output_type -> turbodb.v1.FlushResponse
	22, // 31: turbodb.v1.TurboDBEngine.GetStats:output_type -> turbodb.v1.GetStatsResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_engine_proto_init() }
func file_v1_engine_proto_init() {
	if File_v1_engine_proto != nil {
		return
	}
	file_v1_index_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_engine_proto_rawDesc), len(file_v1_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_engine_proto_goTypes,
		DependencyIndexes: file_v1_engine_proto_depIdxs,
		MessageInfos:      file_v1_engine_proto_msgTypes,
	}.Build()
	File_v1_engine_proto = out.File
	file_v1_engine_proto_goTypes = nil
	file_v1_engine_proto_depIdxs = nil
}
