// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/index.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metric defines the distance metric used for similarity search.
type Metric int32

const (
	Metric_METRIC_UNSPECIFIED   Metric = 0
	Metric_METRIC_INNER_PRODUCT Metric = 1
	Metric_METRIC_COSINE        Metric = 2
	Metric_METRIC_L2            Metric = 3
)

// Enum value maps for Metric.
var (
	Metric_name = map[int32]string{
		0: "METRIC_UNSPECIFIED",
		1: "METRIC_INNER_PRODUCT",
		2: "METRIC_COSINE",
		3: "METRIC_L2",
	}
	Metric_value = map[string]int32{
		"METRIC_UNSPECIFIED":   0,
		"METRIC_INNER_PRODUCT": 1,
		"METRIC_COSINE":        2,
		"METRIC_L2":            3,
	}
)

func (x Metric) Enum() *Metric {
	p := new(Metric)
	*p = x
	return p
}

func (x Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_index_proto_enumTypes[0].Descriptor()
}

func (Metric) Type() protoreflect.EnumType {
	return &file_v1_index_proto_enumTypes[0]
}

func (x Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric.Descriptor instead.
func (Metric) EnumDescriptor() ([]byte, []int) {
	return file_v1_index_proto_rawDescGZIP(), []int{0}
}

// QuantizationVariant selects the TurboQuant algorithm variant.
type QuantizationVariant int32

const (
	QuantizationVariant_QUANTIZATION_VARIANT_UNSPECIFIED QuantizationVariant = 0
	QuantizationVariant_QUANTIZATION_VARIANT_MSE         QuantizationVariant = 1
	QuantizationVariant_QUANTIZATION_VARIANT_PROD        QuantizationVariant = 2
)

// Enum value maps for QuantizationVariant.
var (
	QuantizationVariant_name = map[int32]string{
		0: "QUANTIZATION_VARIANT_UNSPECIFIED",
		1: "QUANTIZATION_VARIANT_MSE",
		2: "QUANTIZATION_VARIANT_PROD",
	}
	QuantizationVariant_value = map[string]int32{
		"QUANTIZATION_VARIANT_UNSPECIFIED": 0,
		"QUANTIZATION_VARIANT_MSE":         1,
		"QUANTIZATION_VARIANT_PROD":        2,
	}
)

func (x QuantizationVariant) Enum() *QuantizationVariant {
	p := new(QuantizationVariant)
	*p = x
	return p
}

func (x QuantizationVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuantizationVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_index_proto_enumTypes[1].Descriptor()
}

func (QuantizationVariant) Type() protoreflect.EnumType {
	return &file_v1_index_proto_enumTypes[1]
}

func (x QuantizationVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuantizationVariant.Descriptor instead.
func (QuantizationVariant) EnumDescriptor() ([]byte, []int) {
	return file_v1_index_proto_rawDescGZIP(), []int{1}
}

// CollectionConfig defines the configuration for a vector collection.
// Validation constraints (enforced at server boundary):
//
//	name:       non-empty, max 128 chars
//	dimension:  1..8192
//	bit_width:  1..8
//	metric:     must not be METRIC_UNSPECIFIED
//	variant:    must not be QUANTIZATION_VARIANT_UNSPECIFIED
type CollectionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	BitWidth      int32                  `protobuf:"varint,3,opt,name=bit_width,json=bitWidth,proto3" json:"bit_width,omitempty"`
	Metric        Metric                 `protobuf:"varint,4,opt,name=metric,proto3,enum=turbodb.v1.Metric" json:"metric,omitempty"`
	Variant       QuantizationVariant    `protobuf:"varint,5,opt,name=variant,proto3,enum=turbodb.v1.QuantizationVariant" json:"variant,omitempty"`
	RotatorSeed   uint64                 `protobuf:"varint,6,opt,name=rotator_seed,json=rotatorSeed,proto3" json:"rotator_seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionConfig) Reset() {
	*x = CollectionConfig{}
	mi := &file_v1_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfig) ProtoMessage() {}

func (x *CollectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfig.ProtoReflect.Descriptor instead.
func (*CollectionConfig) Descriptor() ([]byte, []int) {
	return file_v1_index_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectionConfig) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionConfig) GetBitWidth() int32 {
	if x != nil {
		return x.BitWidth
	}
	return 0
}

func (x *CollectionConfig) GetMetric() Metric {
	if x != nil {
		return x.Metric
	}
	return Metric_METRIC_UNSPECIFIED
}

func (x *CollectionConfig) GetVariant() QuantizationVariant {
	if x != nil {
		return x.Variant
	}
	return QuantizationVariant_QUANTIZATION_VARIANT_UNSPECIFIED
}

func (x *CollectionConfig) GetRotatorSeed() uint64 {
	if x != nil {
		return x.RotatorSeed
	}
	return 0
}

// Vector represents a single vector with its ID and data.
// Validation constraints (enforced at server boundary):
//
//	id:     non-empty
//	values: len == collection.dimension; no NaN/Inf
type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_v1_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_v1_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// QuantizedVector represents a quantized vector in wire format.
type QuantizedVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Codes         []byte                 `protobuf:"bytes,2,opt,name=codes,proto3" json:"codes,omitempty"`
	Norm          float32                `protobuf:"fixed32,3,opt,name=norm,proto3" json:"norm,omitempty"`
	QjlSketch     []byte                 `protobuf:"bytes,4,opt,name=qjl_sketch,json=qjlSketch,proto3" json:"qjl_sketch,omitempty"`            // Only for PROD variant.
	ResidualNorm  float32                `protobuf:"fixed32,5,opt,name=residual_norm,json=residualNorm,proto3" json:"residual_norm,omitempty"` // Only for PROD variant.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuantizedVector) Reset() {
	*x = QuantizedVector{}
	mi := &file_v1_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuantizedVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantizedVector) ProtoMessage() {}

func (x *QuantizedVector) ProtoReflect() protoreflect.Message {
	mi := &file_v1_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantizedVector.ProtoReflect.Descriptor instead.
func (*QuantizedVector) Descriptor() ([]byte, []int) {
	return file_v1_index_proto_rawDescGZIP(), []int{2}
}

func (x *QuantizedVector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuantizedVector) GetCodes() []byte {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *QuantizedVector) GetNorm() float32 {
	if x != nil {
		return x.Norm
	}
	return 0
}

func (x *QuantizedVector) GetQjlSketch() []byte {
	if x != nil {
		return x.QjlSketch
	}
	return nil
}

func (x *QuantizedVector) GetResidualNorm() float32 {
	if x != nil {
		return x.ResidualNorm
	}
	return 0
}

// SearchResult represents a single search result.
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_v1_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_v1_index_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_v1_index_proto protoreflect.FileDescriptor

const file_v1_index_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/index.proto\x12\n" +
	"turbodb.v1\"\xeb\x01\n" +
	"\x10CollectionConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12\x1b\n" +
	"\tbit_width\x18\x03 \x01(\x05R\bbitWidth\x12*\n" +
	"\x06metric\x18\x04 \x01(\x0e2\x12.turbodb.v1.MetricR\x06metric\x129\n" +
	"\avariant\x18\x05 \x01(\x0e2\x1f.turbodb.v1.QuantizationVariantR\avariant\x12!\n" +
	"\frotator_seed\x18\x06 \x01(\x04R\vrotatorSeed\"\xab\x01\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .turbodb.v1.Vector.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x0fQuantizedVector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05codes\x18\x02 \x01(\fR\x05codes\x12\x12\n" +
	"\x04norm\x18\x03 \x01(\x02R\x04norm\x12\x1d\n" +
	"\n" +
	"qjl_sketch\x18\x04 \x01(\fR\tqjlSketch\x12#\n" +
	"\rresidual_norm\x18\x05 \x01(\x02R\fresidualNorm\"\xb5\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.turbodb.v1.SearchResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\\\n" +
	"\x06Metric\x12\x16\n" +
	"\x12METRIC_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14METRIC_INNER_PRODUCT\x10\x01\x12\x11\n" +
	"\rMETRIC_COSINE\x10\x02\x12\r\n" +
	"\tMETRIC_L2\x10\x03*x\n" +
	"\x13QuantizationVariant\x12$\n" +
	" QUANTIZATION_VARIANT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18QUANTIZATION_VARIANT_MSE\x10\x01\x12\x1d\n" +
	"\x19QUANTIZATION_VARIANT_PROD\x10\x02B.Z,github.com/gabrielleeyj/turbodb/api/v1;apiv1b\x06proto3"

var (
	file_v1_index_proto_rawDescOnce sync.Once
	file_v1_index_proto_rawDescData []byte
)

func file_v1_index_proto_rawDescGZIP() []byte {
	file_v1_index_proto_rawDescOnce.Do(func() {
		file_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_index_proto_rawDesc), len(file_v1_index_proto_rawDesc)))
	})
	return file_v1_index_proto_rawDescData
}

var file_v1_index_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_index_proto_goTypes = []any{
	(Metric)(0),              // 0: turbodb.v1.Metric
	(QuantizationVariant)(0), // 1: turbodb.v1.QuantizationVariant
	(*CollectionConfig)(nil), // 2: turbodb.v1.CollectionConfig
	(*Vector)(nil),           // 3: turbodb.v1.Vector
	(*QuantizedVector)(nil),  // 4: turbodb.v1.QuantizedVector
	(*SearchResult)(nil),     // 5: turbodb.v1.SearchResult
	nil,                      // 6: turbodb.v1.Vector.MetadataEntry
	nil,                      // 7: turbodb.v1.SearchResult.MetadataEntry
}
var file_v1_index_proto_depIdxs = []int32{
	0, // 0: turbodb.v1.CollectionConfig.metric:type_name -> turbodb.v1.Metric
	1, // 1: turbodb.v1.CollectionConfig.variant:type_name -> turbodb.v1.QuantizationVariant
	6, // 2: turbodb.v1.Vector.metadata:type_name -> turbodb.v1.Vector.MetadataEntry
	7, // 3: turbodb.v1.SearchResult.metadata:type_name -> turbodb.v1.SearchResult.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_index_proto_init() }
func file_v1_index_proto_init() {
	if File_v1_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_index_proto_rawDesc), len(file_v1_index_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_index_proto_goTypes,
		DependencyIndexes: file_v1_index_proto_depIdxs,
		EnumInfos:         file_v1_index_proto_enumTypes,
		MessageInfos:      file_v1_index_proto_msgTypes,
	}.Build()
	File_v1_index_proto = out.File
	file_v1_index_proto_goTypes = nil
	file_v1_index_proto_depIdxs = nil
}
