// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/kv_cache.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DHead         int32                  `protobuf:"varint,1,opt,name=d_head,json=dHead,proto3" json:"d_head,omitempty"`
	BitWidthKey   int32                  `protobuf:"varint,2,opt,name=bit_width_key,json=bitWidthKey,proto3" json:"bit_width_key,omitempty"`
	BitWidthValue int32                  `protobuf:"varint,3,opt,name=bit_width_value,json=bitWidthValue,proto3" json:"bit_width_value,omitempty"`
	NumHeads      int32                  `protobuf:"varint,4,opt,name=num_heads,json=numHeads,proto3" json:"num_heads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVInitRequest) Reset() {
	*x = KVInitRequest{}
	mi := &file_v1_kv_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVInitRequest) ProtoMessage() {}

func (x *KVInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVInitRequest.ProtoReflect.Descriptor instead.
func (*KVInitRequest) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{0}
}

func (x *KVInitRequest) GetDHead() int32 {
	if x != nil {
		return x.DHead
	}
	return 0
}

func (x *KVInitRequest) GetBitWidthKey() int32 {
	if x != nil {
		return x.BitWidthKey
	}
	return 0
}

func (x *KVInitRequest) GetBitWidthValue() int32 {
	if x != nil {
		return x.BitWidthValue
	}
	return 0
}

func (x *KVInitRequest) GetNumHeads() int32 {
	if x != nil {
		return x.NumHeads
	}
	return 0
}

type KVInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVInitResponse) Reset() {
	*x = KVInitResponse{}
	mi := &file_v1_kv_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVInitResponse) ProtoMessage() {}

func (x *KVInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVInitResponse.ProtoReflect.Descriptor instead.
func (*KVInitResponse) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{1}
}

func (x *KVInitResponse) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type KVQuantizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	TensorData    []byte                 `protobuf:"bytes,2,opt,name=tensor_data,json=tensorData,proto3" json:"tensor_data,omitempty"` // Raw FP16/BF16 tensor bytes.
	NumTokens     int32                  `protobuf:"varint,3,opt,name=num_tokens,json=numTokens,proto3" json:"num_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVQuantizeRequest) Reset() {
	*x = KVQuantizeRequest{}
	mi := &file_v1_kv_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVQuantizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVQuantizeRequest) ProtoMessage() {}

func (x *KVQuantizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVQuantizeRequest.ProtoReflect.Descriptor instead.
func (*KVQuantizeRequest) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{2}
}

func (x *KVQuantizeRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

func (x *KVQuantizeRequest) GetTensorData() []byte {
	if x != nil {
		return x.TensorData
	}
	return nil
}

func (x *KVQuantizeRequest) GetNumTokens() int32 {
	if x != nil {
		return x.NumTokens
	}
	return 0
}

type KVQuantizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QuantizedData   []byte                 `protobuf:"bytes,1,opt,name=quantized_data,json=quantizedData,proto3" json:"quantized_data,omitempty"`
	OriginalBytes   int64                  `protobuf:"varint,2,opt,name=original_bytes,json=originalBytes,proto3" json:"original_bytes,omitempty"`
	CompressedBytes int64                  `protobuf:"varint,3,opt,name=compressed_bytes,json=compressedBytes,proto3" json:"compressed_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KVQuantizeResponse) Reset() {
	*x = KVQuantizeResponse{}
	mi := &file_v1_kv_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVQuantizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVQuantizeResponse) ProtoMessage() {}

func (x *KVQuantizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVQuantizeResponse.ProtoReflect.Descriptor instead.
func (*KVQuantizeResponse) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{3}
}

func (x *KVQuantizeResponse) GetQuantizedData() []byte {
	if x != nil {
		return x.QuantizedData
	}
	return nil
}

func (x *KVQuantizeResponse) GetOriginalBytes() int64 {
	if x != nil {
		return x.OriginalBytes
	}
	return 0
}

func (x *KVQuantizeResponse) GetCompressedBytes() int64 {
	if x != nil {
		return x.CompressedBytes
	}
	return 0
}

type KVDequantizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	QuantizedData []byte                 `protobuf:"bytes,2,opt,name=quantized_data,json=quantizedData,proto3" json:"quantized_data,omitempty"`
	NumTokens     int32                  `protobuf:"varint,3,opt,name=num_tokens,json=numTokens,proto3" json:"num_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDequantizeRequest) Reset() {
	*x = KVDequantizeRequest{}
	mi := &file_v1_kv_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDequantizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDequantizeRequest) ProtoMessage() {}

func (x *KVDequantizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDequantizeRequest.ProtoReflect.Descriptor instead.
func (*KVDequantizeRequest) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{4}
}

func (x *KVDequantizeRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

func (x *KVDequantizeRequest) GetQuantizedData() []byte {
	if x != nil {
		return x.QuantizedData
	}
	return nil
}

func (x *KVDequantizeRequest) GetNumTokens() int32 {
	if x != nil {
		return x.NumTokens
	}
	return 0
}

type KVDequantizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TensorData    []byte                 `protobuf:"bytes,1,opt,name=tensor_data,json=tensorData,proto3" json:"tensor_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDequantizeResponse) Reset() {
	*x = KVDequantizeResponse{}
	mi := &file_v1_kv_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDequantizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDequantizeResponse) ProtoMessage() {}

func (x *KVDequantizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDequantizeResponse.ProtoReflect.Descriptor instead.
func (*KVDequantizeResponse) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{5}
}

func (x *KVDequantizeResponse) GetTensorData() []byte {
	if x != nil {
		return x.TensorData
	}
	return nil
}

type KVDestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandleId      string                 `protobuf:"bytes,1,opt,name=handle_id,json=handleId,proto3" json:"handle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDestroyRequest) Reset() {
	*x = KVDestroyRequest{}
	mi := &file_v1_kv_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDestroyRequest) ProtoMessage() {}

func (x *KVDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDestroyRequest.ProtoReflect.Descriptor instead.
func (*KVDestroyRequest) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{6}
}

func (x *KVDestroyRequest) GetHandleId() string {
	if x != nil {
		return x.HandleId
	}
	return ""
}

type KVDestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDestroyResponse) Reset() {
	*x = KVDestroyResponse{}
	mi := &file_v1_kv_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDestroyResponse) ProtoMessage() {}

func (x *KVDestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kv_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDestroyResponse.ProtoReflect.Descriptor instead.
func (*KVDestroyResponse) Descriptor() ([]byte, []int) {
	return file_v1_kv_cache_proto_rawDescGZIP(), []int{7}
}

var File_v1_kv_cache_proto protoreflect.FileDescriptor

const file_v1_kv_cache_proto_rawDesc = "" +
	"\n" +
	"\x11v1/kv_cache.proto\x12\n" +
	"turbodb.v1\"\x8f\x01\n" +
	"\rKVInitRequest\x12\x15\n" +
	"\x06d_head\x18\x01 \x01(\x05R\x05dHead\x12\"\n" +
	"\rbit_width_key\x18\x02 \x01(\x05R\vbitWidthKey\x12&\n" +
	"\x0fbit_width_value\x18\x03 \x01(\x05R\rbitWidthValue\x12\x1b\n" +
	"\tnum_heads\x18\x04 \x01(\x05R\bnumHeads\"-\n" +
	"\x0eKVInitResponse\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\"p\n" +
	"\x11KVQuantizeRequest\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\x12\x1f\n" +
	"\vtensor_data\x18\x02 \x01(\fR\n" +
	"tensorData\x12\x1d\n" +
	"\n" +
	"num_tokens\x18\x03 \x01(\x05R\tnumTokens\"\x8d\x01\n" +
	"\x12KVQuantizeResponse\x12%\n" +
	"\x0equantized_data\x18\x01 \x01(\fR\rquantizedData\x12%\n" +
	"\x0eoriginal_bytes\x18\x02 \x01(\x03R\roriginalBytes\x12)\n" +
	"\x10compressed_bytes\x18\x03 \x01(\x03R\x0fcompressedBytes\"x\n" +
	"\x13KVDequantizeRequest\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\x12%\n" +
	"\x0equantized_data\x18\x02 \x01(\fR\rquantizedData\x12\x1d\n" +
	"\n" +
	"num_tokens\x18\x03 \x01(\x05R\tnumTokens\"7\n" +
	"\x14KVDequantizeResponse\x12\x1f\n" +
	"\vtensor_data\x18\x01 \x01(\fR\n" +
	"tensorData\"/\n" +
	"\x10KVDestroyRequest\x12\x1b\n" +
	"\thandle_id\x18\x01 \x01(\tR\bhandleId\"\x13\n" +
	"\x11KVDestroyResponse2\x8b\x03\n" +
	"\x11TurboQuantKVCache\x12=\n" +
	"\x04Init\x12\x19.turbodb.v1.KVInitRequest\x1a\x1a.turbodb.v1.KVInitResponse\x12M\n" +
	"\fQuantizeKeys\x12\x1d.turbodb.v1.KVQuantizeRequest\x1a\x1e.turbodb.v1.KVQuantizeResponse\x12O\n" +
	"\x0eQuantizeValues\x12\x1d.turbodb.v1.KVQuantizeRequest\x1a\x1e.turbodb.v1.KVQuantizeResponse\x12O\n" +
	"\n" +
	"Dequantize\x12\x1f.turbodb.v1.KVDequantizeRequest\x1a .turbodb.v1.KVDequantizeResponse\x12F\n" +
	"\aDestroy\x12\x1c.turbodb.v1.KVDestroyRequest\x1a\x1d.turbodb.v1.KVDestroyResponseB.Z,github.com/gabrielleeyj/turbodb/api/v1;apiv1b\x06proto3"

var (
	file_v1_kv_cache_proto_rawDescOnce sync.Once
	file_v1_kv_cache_proto_rawDescData []byte
)

func file_v1_kv_cache_proto_rawDescGZIP() []byte {
	file_v1_kv_cache_proto_rawDescOnce.Do(func() {
		file_v1_kv_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_kv_cache_proto_rawDesc), len(file_v1_kv_cache_proto_rawDesc)))
	})
	return file_v1_kv_cache_proto_rawDescData
}

var file_v1_kv_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_kv_cache_proto_goTypes = []any{
	(*KVInitRequest)(nil),        // 0: turbodb.v1.KVInitRequest
	(*KVInitResponse)(nil),       // 1: turbodb.v1.KVInitResponse
	(*KVQuantizeRequest)(nil),    // 2: turbodb.v1.KVQuantizeRequest
	(*KVQuantizeResponse)(nil),   // 3: turbodb.v1.KVQuantizeResponse
	(*KVDequantizeRequest)(nil),  // 4: turbodb.v1.KVDequantizeRequest
	(*KVDequantizeResponse)(nil), // 5: turbodb.v1.KVDequantizeResponse
	(*KVDestroyRequest)(nil),     // 6: turbodb.v1.KVDestroyRequest
	(*KVDestroyResponse)(nil),    // 7: turbodb.v1.KVDestroyResponse
}
var file_v1_kv_cache_proto_depIdxs = []int32{
	0, // 0: turbodb.v1.TurboQuantKVCache.Init:input_type -> turbodb.v1.KVInitRequest
	2, // 1: turbodb.v1.TurboQuantKVCache.QuantizeKeys:input_type -> turbodb.v1.KVQuantizeRequest
	2, // 2: turbodb.v1.TurboQuantKVCache.QuantizeValues:input_type -> turbodb.v1.KVQuantizeRequest
	4, // 3: turbodb.v1.TurboQuantKVCache.Dequantize:input_type -> turbodb.v1.KVDequantizeRequest
	6, // 4: turbodb.v1.TurboQuantKVCache.Destroy:input_type -> turbodb.v1.KVDestroyRequest
	1, // 5: turbodb.v1.TurboQuantKVCache.Init:output_type -> turbodb.v1.KVInitResponse
	3, // 6: turbodb.v1.TurboQuantKVCache.QuantizeKeys:output_type -> turbodb.v1.KVQuantizeResponse
	3, // 7: turbodb.v1.TurboQuantKVCache.QuantizeValues:output_type -> turbodb.v1.KVQuantizeResponse
	5, // 8: turbodb.v1.TurboQuantKVCache.Dequantize:output_type -> turbodb.v1.KVDequantizeResponse
	7, // 9: turbodb.v1.TurboQuantKVCache.Destroy:output_type -> turbodb.v1.KVDestroyResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_kv_cache_proto_init() }
func file_v1_kv_cache_proto_init() {
	if File_v1_kv_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_kv_cache_proto_rawDesc), len(file_v1_kv_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_kv_cache_proto_goTypes,
		DependencyIndexes: file_v1_kv_cache_proto_depIdxs,
		MessageInfos:      file_v1_kv_cache_proto_msgTypes,
	}.Build()
	File_v1_kv_cache_proto = out.File
	file_v1_kv_cache_proto_goTypes = nil
	file_v1_kv_cache_proto_depIdxs = nil
}
