// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: v1/kv_cache.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TurboQuantKVCache_Init_FullMethodName           = "/turbodb.v1.TurboQuantKVCache/Init"
	TurboQuantKVCache_QuantizeKeys_FullMethodName   = "/turbodb.v1.TurboQuantKVCache/QuantizeKeys"
	TurboQuantKVCache_QuantizeValues_FullMethodName = "/turbodb.v1.TurboQuantKVCache/QuantizeValues"
	TurboQuantKVCache_Dequantize_FullMethodName     = "/turbodb.v1.TurboQuantKVCache/Dequantize"
	TurboQuantKVCache_Destroy_FullMethodName        = "/turbodb.v1.TurboQuantKVCache/Destroy"
)

// TurboQuantKVCacheClient is the client API for TurboQuantKVCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TurboQuantKVCache provides KV cache quantization as a gRPC service,
// an alternative to the in-process CFFI path for vLLM/SGLang.
type TurboQuantKVCacheClient interface {
	Init(ctx context.Context, in *KVInitRequest, opts ...grpc.CallOption) (*KVInitResponse, error)
	QuantizeKeys(ctx context.Context, in *KVQuantizeRequest, opts ...grpc.CallOption) (*KVQuantizeResponse, error)
	QuantizeValues(ctx context.Context, in *KVQuantizeRequest, opts ...grpc.CallOption) (*KVQuantizeResponse, error)
	Dequantize(ctx context.Context, in *KVDequantizeRequest, opts ...grpc.CallOption) (*KVDequantizeResponse, error)
	Destroy(ctx context.Context, in *KVDestroyRequest, opts ...grpc.CallOption) (*KVDestroyResponse, error)
}

type turboQuantKVCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewTurboQuantKVCacheClient(cc grpc.ClientConnInterface) TurboQuantKVCacheClient {
	return &turboQuantKVCacheClient{cc}
}

func (c *turboQuantKVCacheClient) Init(ctx context.Context, in *KVInitRequest, opts ...grpc.CallOption) (*KVInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVInitResponse)
	err := c.cc.Invoke(ctx, TurboQuantKVCache_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboQuantKVCacheClient) QuantizeKeys(ctx context.Context, in *KVQuantizeRequest, opts ...grpc.CallOption) (*KVQuantizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVQuantizeResponse)
	err := c.cc.Invoke(ctx, TurboQuantKVCache_QuantizeKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboQuantKVCacheClient) QuantizeValues(ctx context.Context, in *KVQuantizeRequest, opts ...grpc.CallOption) (*KVQuantizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVQuantizeResponse)
	err := c.cc.Invoke(ctx, TurboQuantKVCache_QuantizeValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboQuantKVCacheClient) Dequantize(ctx context.Context, in *KVDequantizeRequest, opts ...grpc.CallOption) (*KVDequantizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVDequantizeResponse)
	err := c.cc.Invoke(ctx, TurboQuantKVCache_Dequantize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboQuantKVCacheClient) Destroy(ctx context.Context, in *KVDestroyRequest, opts ...grpc.CallOption) (*KVDestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVDestroyResponse)
	err := c.cc.Invoke(ctx, TurboQuantKVCache_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurboQuantKVCacheServer is the server API for TurboQuantKVCache service.
// All implementations must embed UnimplementedTurboQuantKVCacheServer
// for forward compatibility.
//
// TurboQuantKVCache provides KV cache quantization as a gRPC service,
// an alternative to the in-process CFFI path for vLLM/SGLang.
type TurboQuantKVCacheServer interface {
	Init(context.Context, *KVInitRequest) (*KVInitResponse, error)
	QuantizeKeys(context.Context, *KVQuantizeRequest) (*KVQuantizeResponse, error)
	QuantizeValues(context.Context, *KVQuantizeRequest) (*KVQuantizeResponse, error)
	Dequantize(context.Context, *KVDequantizeRequest) (*KVDequantizeResponse, error)
	Destroy(context.Context, *KVDestroyRequest) (*KVDestroyResponse, error)
	mustEmbedUnimplementedTurboQuantKVCacheServer()
}

// UnimplementedTurboQuantKVCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTurboQuantKVCacheServer struct{}

func (UnimplementedTurboQuantKVCacheServer) Init(context.Context, *KVInitRequest) (*KVInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedTurboQuantKVCacheServer) QuantizeKeys(context.Context, *KVQuantizeRequest) (*KVQuantizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuantizeKeys not implemented")
}
func (UnimplementedTurboQuantKVCacheServer) QuantizeValues(context.Context, *KVQuantizeRequest) (*KVQuantizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuantizeValues not implemented")
}
func (UnimplementedTurboQuantKVCacheServer) Dequantize(context.Context, *KVDequantizeRequest) (*KVDequantizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dequantize not implemented")
}
func (UnimplementedTurboQuantKVCacheServer) Destroy(context.Context, *KVDestroyRequest) (*KVDestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedTurboQuantKVCacheServer) mustEmbedUnimplementedTurboQuantKVCacheServer() {}
func (UnimplementedTurboQuantKVCacheServer) testEmbeddedByValue()                           {}

// UnsafeTurboQuantKVCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurboQuantKVCacheServer will
// result in compilation errors.
type UnsafeTurboQuantKVCacheServer interface {
	mustEmbedUnimplementedTurboQuantKVCacheServer()
}

func RegisterTurboQuantKVCacheServer(s grpc.ServiceRegistrar, srv TurboQuantKVCacheServer) {
	// If the following call panics, it indicates UnimplementedTurboQuantKVCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TurboQuantKVCache_ServiceDesc, srv)
}

func _TurboQuantKVCache_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboQuantKVCacheServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboQuantKVCache_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboQuantKVCacheServer).Init(ctx, req.(*KVInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboQuantKVCache_QuantizeKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVQuantizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboQuantKVCacheServer).QuantizeKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboQuantKVCache_QuantizeKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboQuantKVCacheServer).QuantizeKeys(ctx, req.(*KVQuantizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboQuantKVCache_QuantizeValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVQuantizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboQuantKVCacheServer).QuantizeValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboQuantKVCache_QuantizeValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboQuantKVCacheServer).QuantizeValues(ctx, req.(*KVQuantizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboQuantKVCache_Dequantize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVDequantizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboQuantKVCacheServer).Dequantize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboQuantKVCache_Dequantize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboQuantKVCacheServer).Dequantize(ctx, req.(*KVDequantizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurboQuantKVCache_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboQuantKVCacheServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurboQuantKVCache_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboQuantKVCacheServer).Destroy(ctx, req.(*KVDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TurboQuantKVCache_ServiceDesc is the grpc.ServiceDesc for TurboQuantKVCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TurboQuantKVCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turbodb.v1.TurboQuantKVCache",
	HandlerType: (*TurboQuantKVCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _TurboQuantKVCache_Init_Handler,
		},
		{
			MethodName: "QuantizeKeys",
			Handler:    _TurboQuantKVCache_QuantizeKeys_Handler,
		},
		{
			MethodName: "QuantizeValues",
			Handler:    _TurboQuantKVCache_QuantizeValues_Handler,
		},
		{
			MethodName: "Dequantize",
			Handler:    _TurboQuantKVCache_Dequantize_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _TurboQuantKVCache_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/kv_cache.proto",
}
